name: Backend CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Clean and install dependencies
      - name: Clean and install dependencies
        run: |
          cd api
          rm -rf node_modules  # Remove any pre-existing node_modules
          npm install

      # Step 4: Verify Jest is installed
      - name: Verify Jest installation
        run: |
          cd api
          ls -alh node_modules/.bin  # List files in the .bin directory to confirm Jest is installed

      # Step 5: Run tests
      - name: Run Tests
        run: |
          cd api
          npm test
